#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND %BUILD_REQ);

%BUILD_REQ = (
   'Test::More'          => '0.40',
   'Test::Sys::Info'     => '0.11',
);

%PREREQ = (
   'IO::File'            => 0,
   'Linux::Distribution' => 0,
   'Unix::Processors'    => 0,
   'Sys::Info::Base'     => '0.69_05',
);

1;

__END__
